src/Entity/Marker.php
<?php

namespace App\Entity;

use App\Repository\MarkerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MarkerRepository::class)
 */
class Marker
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $x;

    /**
     * @ORM\Column(type="integer")
     */
    private $z;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=MarkerType::class, inversedBy="markers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $icon;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $icon_width;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $icon_height;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $icon_anchor;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_author;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $underground;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getX(): ?int
    {
        return $this->x;
    }

    public function setX(int $x): self
    {
        $this->x = $x;

        return $this;
    }

    public function getZ(): ?int
    {
        return $this->z;
    }

    public function setZ(int $z): self
    {
        $this->z = $z;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getType(): ?MarkerType
    {
        return $this->type;
    }

    public function setType(?MarkerType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(?string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    public function getIconWidth(): ?int
    {
        return $this->icon_width;
    }

    public function setIconWidth(?int $icon_width): self
    {
        $this->icon_width = $icon_width;

        return $this;
    }

    public function getIconHeight(): ?int
    {
        return $this->icon_height;
    }

    public function setIconHeight(?int $icon_height): self
    {
        $this->icon_height = $icon_height;

        return $this;
    }

    public function getIconAnchor(): ?int
    {
        return $this->icon_anchor;
    }

    public function setIconAnchor(?int $icon_anchor): self
    {
        $this->icon_anchor = $icon_anchor;

        return $this;
    }

    public function getImageAuthor(): ?string
    {
        return $this->image_author;
    }

    public function setImageAuthor(?string $image_author): self
    {
        $this->image_author = $image_author;

        return $this;
    }

    public function getUnderground(): ?int
    {
        return $this->underground;
    }

    public function setUnderground(?int $underground): self
    {
        $this->underground = $underground;

        return $this;
    }
}

templates/admin.html.twig
{# templates/index.html.twig #}
{% extends "base.html.twig" %}

{% block body %}
<div id="admin">
	{% for message in app.flashes('success') %}
		<div class="alert alert-success">
			{{ message }}
		</div>
	{% endfor %}
	{% for message in app.flashes('error') %}
		<div class="alert alert-warning">
			{{ message }}
		</div>
	{% endfor %}
	<div id="map"></div>
	<h1>Create new Marker</h1>
	<hr>
	<form method="post" action="/admin/new">
		<div class="row">
			<div class="col-md-3">
				<label for="type">Choose Marker Type</label>
			</div>
			<div class="col-md-7">
				<select name="type" id="markertypeselect">
					{% for mt in markerTypes %}
						{% if mt.children|length < 1 %}
				 			<option value="{{ mt.id }}">{{ mt.title }}</option>
						{% endif %}
				 	{% endfor %}
				</select>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="x">x coordinate</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="x" style="width:100px; margin-bottom: 5px"></input>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3">
				<label for="z">z coordinate</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="z" style="width:100px"></input>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="title">Title</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="title"></input>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="description">Description</label>
			</div>
			<div class="col-md-7">
				<textarea name="description" rows="4" cols="50"></textarea>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="image">Image</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="image"></input>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3">
				<label for="image_author">Image Author</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="image_author"></input>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="icon">Icon</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="icon" value="{{ markerTypes[0].icon }}" id="markertypeicon"></input>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="icon_width">Icon Width</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="icon_width" placeholder="{{ markerTypes[0].iconwidth }}" style="width: 80px" id="markertypeiconwidth"></input>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="icon_height">Icon Height</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="icon_height" placeholder="{{ markerTypes[0].iconheight }}" style="width: 80px" id="markertypeiconheight"></input>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="icon_anchor">Icon Anchor</label>
			</div>
			<div class="col-md-7">
				<input type="text" name="icon_anchor" placeholder="{{ markerTypes[0].iconanchor }}" style="width: 80px" id="markertypeiconanchor"></input>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
				<label for="icon_anchor">Underground</label>
			</div>
			<div class="col-md-7">
				<input type="checkbox" name="underground"></input>
			</div>
		</div>
		<br>
		<button type="submit" class="btn btn-success">Go</button>
	</form>
</div>
<div id="markerTypes">
	{% for mt in markerTypes %}
		{% if mt.displayInControls %}
			<div
			data-id="{{ mt.id }}"
			data-title="{{ mt.title }}"
			data-parent="{% if mt.parent %}{{ mt.parent.id }}{% endif %}"
			data-icon="{{ mt.icon }}"
			data-icon-width="{{ mt.iconwidth }}"
			data-icon-height="{{ mt.iconheight }}"
			data-icon-anchor="{{ mt.iconanchor }}"
			data-disabled="{{ mt.disabled }}"
			></div>
		{% endif %}
	{% endfor %}
</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="flattr:id" content="vjdoyj"> 
        <title>{% block title %}Interactive Meadow Map{% endblock %}</title>
        <link rel="shortcut icon" type="image/png" href="{{ asset('img/favicon.png') }}"/>
        {% block stylesheets %}
            <!-- Bootstrap, FontAwesome, Nunito Sans -->
			<link href="{{ asset('fa/css/all.css') }}" rel="stylesheet">
        	<link href="{{ asset('twbs/bootstrap/dist/css/bootstrap.css') }}" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
             <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
			   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
			   crossorigin=""/>

            <!-- Custom CSS -->
            <link href="{{ asset('css/main.css') }}" rel="stylesheet">
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}
            <!-- JQuery, Leaflet -->
        	<script src="{{ asset('js/jquery.js') }}"></script>
			<script>L_DISABLE_3D = true;</script>
          <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
			   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
			   crossorigin=""></script>
          <script src="{{ asset('js/easyprint/bundle.js') }}"></script>
			   <script src="{{ asset('js/jquery-ui.min.js') }}"></script>
			   <script src="{{ asset('js/jquery.awesome-cursor.js') }}"></script>

            <!-- Custom JS -->
            <script src="{{ asset('js/main.js') }}"></script>
            
            <!-- Cookie Notice -->
            <script src="{{ asset('js/cookie.notice.js') }}"></script>
            <!-- <script>
                new cookieNoticeJS({
                   // Localizations of the notice message
                   'messageLocales': {
                     'en': 'Um Ihnen ein optimales Erlebnis auf unserer Website zu bieten, nutzen wir Cookies. Lesen Sie mehr über unsere Verwendungszwecke in unserer'
                   },
                  
                   // Localizations of the dismiss button text
                   'buttonLocales': {
                     'en': 'Akzeptieren'
                   },
                   
                   // Shows the "learn more button (default=false)
                   'learnMoreLinkEnabled':true,
                   
                   // The href of the learn more link must be applied if (learnMoreLinkEnabled=true) 
                   'learnMoreLinkHref':'/privacy',
                   
                   // Text for optional learn more button
                   'learnMoreLinkText':{
                       'en':'Datenschutzerklärung.'
                   },
                   
                   // Dismiss button background color
                   'buttonBgColor': '#fff',  
                   
                   // Dismiss button text color
                   'buttonTextColor': '#196bba', 
                     
                   // Notice background color
                   'noticeBgColor': '#196bba', 
                      
                   // Notice text color
                   'noticeTextColor': '#fff', 
                   
                   // the lernMoreLink color (default='#009fdd') 
                   'linkColor':'#dddddd'
                      
                }); -->
</script>
        {% endblock %}
    </body>
</html>

templates/imprint.html.twig
{# templates/index.html.twig #}
{% extends "base.html.twig" %}

{% block body %}
<div id="admin">
        <h2>Imprint</h2>
        
        Interactive Meadow Map is a web service hosted in Germany and thus requires an "Impressum". So, let's get it over and done with. The service is provided by:<br><br>
        Nicholas Ulmke<br>
        August-Bebel-Str. 25<br>
        63225 Langen<br>
        Germany<br><br>

        Glad about any fan mail ¯\_(ツ)_/¯

</div>
{% endblock %}

templates/index.html.twig
{# templates/index.html.twig #}
{% extends "base.html.twig" %}

{% block body %}
<div id="loading-overlay">
	<img src="/img/spinner.svg" style="width: 25px" /> <span>Preparing Download...</span>
</div>
<div id="map"></div>
<div id="menu">
	<div id="sidemenu-marker">
		<div class="btn-marker">
			<div class="btn-marker-actualbutton">
				<i class="fas fa-map-marker-alt"></i> <span class="btn-marker-text">Add Marker</span>
			</div>
			<div class="marker-subcontent">
				<div class="marker-color-buttons">
					<div class="marker-color-button active" data-color="red">
						<i class="fas fa-map-marker-alt" style="color: #FF4136"></i>
					</div>
					<div class="marker-color-button" data-color="green">
						<i class="fas fa-map-marker-alt" style="color: #2ECC40"></i>
					</div>
					<div class="marker-color-button" data-color="yellow">
						<i class="fas fa-map-marker-alt" style="color: #FFDC00"></i>
					</div>
					<div class="marker-color-button" data-color="blue">
						<i class="fas fa-map-marker-alt" style="color: #0074D9"></i>
					</div>
					<div class="marker-color-button" data-color="orange">
						<i class="fas fa-map-marker-alt" style="color: #FF851B"></i>
					</div>
					<div class="marker-color-button" data-color="purple">
						<i class="fas fa-map-marker-alt" style="color: #B10DC9"></i>
					</div>
				</div>
				Click a position on the map or paste coordinates from the game. Coordinates can be copied to your clipboard by pressing <strong>Shift + G</strong> while in game.
				<div class="btn-clear">
					Clear all
				</div>
				<input type="text" class="input-coordinates" placeholder="(x,y,z)"/>
				<div class="btn-insert">
					Insert
				</div>
			</div>
		</div>
	</div>
	<div id="sidemenu-export">
		<div class="btn-export">
			<i class="fas fa-download"></i> Export
		</div>
	</div>
	<div class="menu-top row">
		<div class="col-md-6">
			<h1>Interactive Meadow Map <small>by Nemo and c42</small></h1>
		</div>
		<div class="col-md-6">
			<div class="togglemenu">
				<span>Click here to filter layers and for more information</span> <i class="fas fa-chevron-up"></i>
			</div>
		</div>
	</div>
	<div class="menu-content row">
		<div class="col-md-5 menu-info">
			This purely fan-made project aims at providing Meadow users with a precise map with as many details as possible. The borders of the map and all markers are precisely positioned, using game coordinates as a reference, the maps North however corresponds to in game East. All names used on the map are not official. The use of the textures has been approved by the game developers. The map will be kept updated as new content is released. Check out our <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2276192929">page on Steam</a> for future plans. The work poured into this project is and will continue to be a hobby, if you however wish to show support, I have set up a <a href="https://flattr.com/@meadowmap">Flattr page</a> for donations to cover server costs only. We hope our map helps you navigate through the world of Meadow - see you in game!
			<div class="menu-links">
				<span>© Copyright 2021, last updated January 12th 2021</span>
				<a href="/imprint">Imprint</a>
				<a href="/privacy">Privacy</a>
				<a href="https://flattr.com/@meadowmap">Flattr</a>
				<a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2276192929">Plans</a>
			</div>
		</div>
		<div class="col-md-7 menu-filters row">
			<div class="single-filters">
				<div class="filter">
					<div class="filter-upper">
						<img class="filter-icon" src="/img/icon_textures.png" />
						<label>Textures <input type="checkbox" checked data-layer="Textures"></label> <i class="filter-check fas fa-check"></i>
					</div>
				</div>
				<div class="filter">
					<div class="filter-upper">
						<img class="filter-icon" src="/img/icon_inclines.png" />
						<label>Inclines <input type="checkbox" checked data-layer="Inclines"></label> <i class="filter-check fas fa-check"></i>
					</div>
				</div>
				<div class="filter">
					<div class="filter-upper">
						<img class="filter-icon" src="/img/icon_rises.png" />
						<label>Rises <input type="checkbox" checked data-layer="Rises"></label> <i class="filter-check fas fa-check"></i>
					</div>
				</div>
				<div class="filter">
					<div class="filter-upper">
						<img class="filter-icon" src="/img/icon_foliage.png" />
						<label>Catnip and Puffballs <input type="checkbox" checked data-layer="Catnip and Puffballs"></label> <i class="filter-check fas fa-check"></i>
					</div>
				</div>
			</div>
			{% for mt in markerTypes %}
				{% if not mt.parent %}
					<div class="filter{% if mt.children|length > 0 %} col filter-parent row{% endif %}" data-id="{{ mt.id }}" {% if not mt.displayInControls %}style="display:none"{% endif %}>
						<div class="filter-upper">
							<img class="filter-icon" src="{{ mt.icon }}" />
							<label>{{ mt.title }} <input type="checkbox" {% if mt.defaultshow and not mt.disabled %}checked{% endif %} data-layer="{{ mt.title }}"></label> <i class="filter-check fas fa-check" {% if (not mt.defaultshow) or mt.disabled %}style="opacity: 0.3"{% endif %}></i>
						</div>
						{% if mt.children|length > 0 %}
							{% for child in mt.children %}
								{% if loop.index0 % 6 == 0 %}
									<div class="col filter-children-group">
								{% endif %}
									<div class="filter filter-child" data-id="{{ child.id }}" {% if not mt.displayInControls %}style="display:none"{% endif %}>
										<img class="filter-icon" src="{{ child.icon }}" />
										<label {% if child.disabled %}style="color: #ffc5c5"{% endif %}>{{ child.title }} <input type="checkbox" {% if child.defaultshow and not child.disabled %}checked{% endif %} data-layer="{{ child.title }}"></label> <i class="filter-check fas fa-check" {% if (not child.defaultshow) or child.disabled %}style="opacity: 0.3"{% endif %}></i>
									</div>
								{% if loop.index0 % 6 == 5 %}
									</div>
								{% endif %}
							{% endfor %}
							
								</div>
							
						{% endif %}
					</div>
				{% endif %}
			{% endfor %}
		</div>
	</div>
</div>
<div id="markerTypes">
	{% for mt in markerTypes %}
			<div
			data-id="{{ mt.id }}"
			data-title="{{ mt.title }}"
			data-parent="{% if mt.parent %}{{ mt.parent.id }}{% endif %}"
			data-icon="{{ mt.icon }}"
			data-defaultshow="{{ mt.defaultshow }}"
			data-disabled="{{ mt.disabled }}"
			></div>
	{% endfor %}
</div>
<div id="markers">
	{% for m in markers %}
			<div
			data-type="{{ m.type.title }}"
			data-x="{{ m.x }}"
			data-z="{{ m.z }}"
			data-title="{{ m.title }}"
			data-description="{{ m.description }}"
			data-image="{{ m.image }}"
			data-image-author="{{ m.imageAuthor }}"
			data-icon="{% if m.icon %}{{ m.icon }}{% else %}{{ m.type.icon }}{% endif %}"
			data-icon-width="{% if m.iconWidth %}{{ m.iconWidth }}{% elseif m.type.iconWidth %}{{ m.type.iconWidth }}{% elseif m.type.parent.iconWidth %}{{ m.type.parent.iconWidth }}{% else %}50{% endif %}"
			data-icon-height="{% if m.iconHeight %}{{ m.iconHeight }}{% elseif m.type.iconHeight %}{{ m.type.iconHeight }}{% elseif m.type.parent.iconHeight %}{{ m.type.parent.iconHeight }}{% else %}50{% endif %}"
			data-icon-anchor="{% if m.iconAnchor != null %}{{ m.iconAnchor }}{% elseif m.type.iconAnchor != null %}{{ m.type.iconAnchor }}{% elseif m.type.parent and m.type.parent.iconAnchor != null %}{{ m.type.parent.iconAnchor }}{% else %}25{% endif %}"
			data-disabled="{{ m.type.disabled }}"
			data-underground="{{ m.underground }}"
			data-background="{% if m.type.background %}{{ m.type.background }}{% else %}0{% endif %}"
			></div>
	{% endfor %}
</div>
{% endblock %}